---
language: python
services: docker

before_install: # https://docs.travis-ci.com/user/docker/#installing-a-newer-docker-version
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
  # Install test dependencies.
  - pip install ansible molecule[docker] yamllint ansible-lint testinfra docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-matrix-synapse udelarinterior.matrix_synapse
  - cd udelarinterior.matrix_synapse

script:
  # Run tests.
  - molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
