---

- block:
  - name: Ensure postfix is installed
    apt:
      name: postfix
      state: present
    when: synapse_smtp_host == 'localhost'

  - name: Configure postfix
    template:
      src: etc/postfix/main.cf.j2
      dest: /etc/postfix/main.cf
      mode: 0644
      owner: root
      group: root
    notify: restart postfix
    when: synapse_smtp_host == 'localhost'

  - name: Configure Synapse mailing
    template:
      src: "{{ synapse_confd_templates_src }}/email.yaml.j2"
      dest: "{{ synapse_installation_path }}/conf.d/email.yaml"
      mode: 0644
      owner: root
      group: root
    notify: restart matrix-synapse
  when: synapse_email_enable | bool

- name: Disable mailing
  file:
    path: "{{ synapse_installation_path }}/conf.d/email.yaml"
    state: absent
  notify: restart matrix-synapse
  when: not synapse_email_enable | bool

- name: Copy custom email templates to server
  synchronize:
    src: "{{ synapse_email_templates_src }}"
    dest: "{{ synapse_email_templates_dest }}"
    owner: no
    group: no
  when: synapse_email_with_custom_templates | bool