---

- block:
  - name: Install LDAP authentication provider module
    when: synapse_installation_method == "source"
    pip:
      name: matrix-synapse-ldap3
      chdir: "{{ synapse_installation_path }}"
      virtualenv: "{{ synapse_installation_path }}/env"
      virtualenv_python: python3
      state: "{{ synapse_pip_state }}"

  - name: Configure LDAP integration
    template:
      src: "{{ synapse_confd_templates_src }}/ldap.yaml.j2"
      dest: "{{ synapse_config_path }}/conf.d/ldap.yaml"
      mode: 0644
      owner: root
      group: root
    notify: restart matrix-synapse
  when: synapse_with_ldap_authentication | bool

- name: Disable LDAP integration
  file:
    path: "{{ synapse_config_path }}/conf.d/ldap.yaml"
    state: absent
  notify: restart matrix-synapse
  when: not synapse_with_ldap_authentication | bool
