---

## Based on https://github.com/matrix-org/synapse/blob/master/docs/postgres.rst

- name: Install PostgreSQL and dependencies
  apt:
    name:
      - postgresql
      - libpq-dev
      - "{{ 'python-psycopg2' if(ansible_distribution_major_version is version('10', '<=')) else 'python3-psycopg2' }}"
    state: present

- name: Ensure PostgreSQL service is started
  service:
    name: postgresql
    state: started

- name: Install Synapse PostgreSQL library
  when: synapse_installation_method == "source"
  pip:
    name: matrix-synapse[postgres]
    chdir: "{{ synapse_installation_path }}"
    virtualenv: "{{ synapse_installation_path }}/env"
    virtualenv_python: python3
    state: present

- name: Create Synapse PostgreSQL user
  become: true
  become_user: postgres
  postgresql_user:
    name: "{{ synapse_psql_user }}"
    password: "{{ synapse_psql_password }}"

- name: Create PostgreSQL Database
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ synapse_psql_db_name }}"
    encoding: UTF-8
    lc_collate: C
    lc_ctype: C
    template: template0
    owner: "{{ synapse_psql_user }}"

- name: Enable/disable PostgreSQL Database
  template:
    src: "{{ synapse_confd_templates_src }}/database.yaml.j2"
    dest: "{{ synapse_installation_path }}/conf.d/database.yaml"
    mode: 0644
    owner: root
    group: root
  notify: restart matrix-synapse
