---

- name: Configure server notices
  template:
    src: "{{ synapse_confd_templates_src }}/server_notices.yaml.j2"
    dest: "{{ synapse_installation_path }}/conf.d/server_notices.yaml"
    mode: 0644
    owner: root
    group: root
  notify: restart matrix-synapse
  when: synapse_installation_with_server_notices | bool

- name: Disable server notices
  file:
    path: "{{ synapse_installation_path }}/conf.d/server_notices.yaml"
    state: absent
  notify: restart matrix-synapse
  when: not synapse_installation_with_server_notices | bool