---

# Guia de instalacion: https://github.com/Awesome-Technologies/synapse-admin?tab=readme-ov-file#step-by-step-install

- name: Create public directory for Synapse Admin
  file:
    path: "{{ synapse_admin_installation_path_web }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Download and unpack Synapse Admin
  unarchive:
    remote_src: yes
    src: https://github.com/Awesome-Technologies/synapse-admin/releases/download/{{ synapse_admin_version }}/synapse-admin-{{ synapse_admin_version }}.tar.gz
    dest: "{{ synapse_admin_installation_path_web }}"
    owner: root
    group: root
    mode: 0755

- name: Ensure git is installed
  apt:
    name: git
    state: present

- name: Ensure curl is installed
  package:
    name: curl
    state: present

- name: Run NodeSource setup script via curl and bash
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -

- name: Install Node.js
  apt:
    name: nodejs
    state: present

- name: Install Yarn globally using the npm module
  npm:
    name: yarn
    global: true
    state: present

- name: Download synapse-admin source code
  git:
    repo: https://github.com/Awesome-Technologies/synapse-admin.git
    dest: "{{ synapse_admin_installation_path }}"
    clone: yes
    update: yes
    force: yes

- name: Download specific yarn version
  shell:
    cmd: yarn set version berry
    chdir: "{{ synapse_admin_installation_path }}"

- name: Download dependencies
  shell:
    cmd: yarn install
    chdir: "{{ synapse_admin_installation_path }}"

- name: Install Docker
  include_tasks: install_docker.yml

- name: Set nginx configuration file
  template:
    src: "etc/nginx/sites-available/synapse_admin.j2"
    dest: /etc/nginx/sites-available/{{ synapse_admin_server_name }}.conf
    mode: 0644
    owner: root
    group: root
  notify: restart nginx

- name: Ensure that Synapse admin site is enabled
  file:
    path: /etc/nginx/sites-enabled/{{ synapse_admin_server_name }}.conf
    src: /etc/nginx/sites-available/{{ synapse_admin_server_name }}.conf
    state: link
  notify: restart nginx

- name: Set port docker container
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ synapse_admin_installation_path }}/docker-compose.yml"
    mode: 0644
    owner: root
    group: root

- name: Run docker container
  shell:
    cmd: docker compose up -d
    chdir: "{{ synapse_admin_installation_path }}"
